### ISSUE TITLE
Preview af video på FB

### ISSUE THREAD

**Issue by Kennik89** [Thanerik/Wign#30]
Flere skrev af og til at de ikke kan "få adgang" til wign hjemmesiden. Dog viste det sig at de faktisk bare ikke kunne se nogen på FBs preview, hvor den viser video af et (mest populær?) tegn?

![image](https://cloud.githubusercontent.com/assets/8750653/14761184/01d59f58-0959-11e6-8802-79fed4cad27f.png)

**Comment by Thanerik** [comment]
Yeps. Jeg ordnede Open Graph, så Facebook kan vise den mest populær tegn af en bestemt ord hvis man deler siden. Dog virker video-delen ikke optimalt :disappointed: Kigger på det!

**Comment by Thanerik** [comment]
Solved!
